"$schema" = 'https://starship.rs/config-schema.json'

format = "$nix_shell[](fg:green)$directory[](fg:green bg:cyan)$git_branch[](cyan) "

scan_timeout = 60
command_timeout = 3600
add_newline = false

[nix_shell]
format = "[](fg:#5277C2)[ Shell](bg:#5277C2 fg:#ffffff)[](fg:#5277C2) "

[directory]
truncate_to_repo = false
format = "[󰉋 $path ](bg:green fg:#ffffff)"

[git_branch]
format = "[  $branch ](bg:cyan fg:#ffffff)"
