# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "λ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[λ](bold green)"     
error_symbol = "[λ](bold red)"
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

