# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ffd3d131-071e-47ee-bd0e-cfe7cc9392ec";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/00ED-71DC";
      fsType = "vfat";
    };

  fileSystems."/mnt/mint" =
    { device = "/dev/disk/by-uuid/09f440d8-52bc-40ed-8b14-a06c8be6e28d";
      fsType = "ext4";
    };

  fileSystems."/mnt/4tb" =
    { device = "/dev/disk/by-uuid/4850DDDA50DDCF36";
      fsType = "ntfs";
    };

  fileSystems."/mnt/ssd1" =
    { device = "/dev/disk/by-uuid/648CD8628CD83072";
      fsType = "ntfs";
    };

  fileSystems."/mnt/ssd2" =
    { device = "/dev/disk/by-uuid/90C8CBFBC8CBDD9A";
      fsType = "ntfs";
    };

  fileSystems."/mnt/win" =
    { device = "/dev/disk/by-uuid/EC227B91227B5F8E";
      fsType = "ntfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
