#!/usr/bin/env bash
#waybar -c $HOME/.config/hypr/component/waybar/config -s $HOME/.config/hypr/component/waybar/style.css &

waybar -c $HOME/.config/waybar/config -s $HOME/.config/waybar/style.css &

