#!/usr/bin/env bash

images_path=~/Pictures/wallpapers/ 
variations=(lsd.png dmt.png mdma.png cocaine.png)
number=$(($RANDOM % 4))
image=${variations[$number]}
wallpaper=$images_path$image
swww_fork=~/.config/hypr/scripts/tools/swww
$swww_fork init
$swww_fork img $wallpaper --transition-type grow --transition-pos 0.9,0.1 --transition-duration 2
