#!/usr/bin/env bash

images_path=~/flake/home/graphical/wms/hyprland/wallpapers/
variations=(programmer.gif eye.jpg)
number=$(($RANDOM % 4))
image=${variations[$number]}
wallpaper=$images_path$image
swww init
swww img $wallpaper --transition-type grow --transition-pos 0.9,0.1 --transition-duration 2 --transition-fps 90
