#!/usr/bin/env bash

#autostart
pgrep -x sxhkd > /dev/null || sxhkd &
pkill picom
picom -b
#feh --bg-fill ~/Pictures/wall/1.jpg
xrandr --output DP-0 --mode 1920x1080 --rate 165
nitrogen --restore &
flameshot &

~/.config/polybar/launch.sh

#monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#window information
bspc config border_width 0 
bspc config window_gap 9
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

#rules
bspc rule -a mumble state=floating follow=on focus=on

#keyboard
xset r rate 150 25
