#!/usr/bin/env bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# waybar
$scripts/launch_waybar &
$scripts/tools/dynamic &

# wallpaper
#swww kill
#swww init
#swww img ~/Pictures/wallpapers/lsd.png &
hyprpaper &

#dunst (notifications)
dunst &

# cursor
#hyprctl setcursor "Catppuccin-Mocha-Mauve-Cursors" 24
#hyprctl setcursor "macOS-BigSur" 24
# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
