#!/usr/bin/env bash

images_path=~/flake/home/desktop/graphical/wms/hyprland/wallpapers/
variations=(1.jpg 2.jpg anime.png programmer.gif tokyonight-mchouse.png catppuccin.png lofi.gif waterfall.gif cityscape.jpg nix.png nixos.png oxocarbon.png jabuti.png)
number=$(($RANDOM % 20))
image=${variations[$number]}
wallpaper=$images_path$image
swww init
swww img $wallpaper --transition-type grow --transition-pos 0.9,0.1 --transition-duration 1.5 --transition-fps 90
